services:
  - type: web
    name: kpi-master-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build
    startCommand: gunicorn --chdir api app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
  - type: web
    name: kpi-master-frontend
    env: static
    buildCommand: cd frontend && npm run render-build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html