services:
  - type: web
    name: kpi-master-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential libatlas-base-dev gfortran
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
  - type: web
    name: kpi-master-frontend
    env: static
    buildCommand: cd frontend && npm run render-build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html